### ISSUE TITLE
Home Assistant Deprecating Feature in Use

### ISSUE THREAD

**Issue by theharshl** [UngluedChalice/htd-lync12-home-assistant#1]
I recently installed this integration and noticed upon adding all of my zones and sources that a deprecated feature is being used and needs to be moved:

2024-08-19 23:27:52.505 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.htd_lync12.media_player.HtdDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|SELECT_SOURCE: 2444>, please report it to the author of the 'htd_lync12' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

This is repeated 12 times, once for each zone I presume.

**Comment by UngluedChalice** [comment]
You happen to find a fix for this? I have no clue.

**Comment by theharshl** [comment]
LOL!

This integration is using a feature in Home Assistant that is being deprecated. So whatever that feature is doing the code for this project will need to be adjusted to use the Home Assistant feature that has replaced it, otherwise the integration will break, presumably with the January release.

To more directly answer your question, no, I am not a programmer, so I do not know how to fork this project and fix this.

I would be very interested in participating in pooling money to have a proper integration for HTD created. There was one I used in HomeSeer for years that was fantastic. It would be great to have this one brought up to snuff by someone with the skills and I would be happy to contribute to the cause.

**Comment by Noobitious** [comment]
I tried to edit the code on my own system but my Python edits didn't work. It wasn't as simple as replacing the words with the new words. We need someone to assist. These are my log messages, if they help.

Log message 1:

Entity None (<class 'custom_components.htd_lync12.media_player.HtdDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|SELECT_SOURCE: 2444>, please report it to the author of the 'htd_lync12' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Log message 2:

Logger: homeassistant.components.media_player.const
Source: helpers/deprecation.py:222
integration: Media player (documentation, issues)
First occurred: 1:21:24 PM (5 occurrences)
Last logged: 1:21:24 PM

SUPPORT_SELECT_SOURCE was used from htd_lync12, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.SELECT_SOURCE instead, please report it to the author of the 'htd_lync12' custom integration
SUPPORT_TURN_OFF was used from htd_lync12, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.TURN_OFF instead, please report it to the author of the 'htd_lync12' custom integration
SUPPORT_TURN_ON was used from htd_lync12, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.TURN_ON instead, please report it to the author of the 'htd_lync12' custom integration
SUPPORT_VOLUME_MUTE was used from htd_lync12, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_MUTE instead, please report it to the author of the 'htd_lync12' custom integration
SUPPORT_VOLUME_SET was used from htd_lync12, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_SET instead, please report it to the author of the 'htd_lync12' custom integration

**Comment by UngluedChalice** [comment]
@Noobitious and @theharshl please try the updated media_player.py and see if you get any errors. Please report back!

**Comment by Noobitious** [comment]
First, I really appreciate you modifying it for 6 zone as I previously did that in a more hacky way.  

Re the recent version: The good news is no more start up log errors. 

The bad news is when I attempt to run a script that was working before I get this:
```
Logger: homeassistant
Source: custom_components/htd_lync12/media_player.py:101
integration: HTD Lync12 Series
First occurred: 9:43:19 PM (8 occurrences)
Last logged: 9:44:29 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1046, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 962, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1125, in state_attributes
    if (value := getattr(self, attr)) is not None:
                 ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/htd_lync12/media_player.py", line 101, in volume_level
    return self.zone_info['vol'] / MAX_HTD_VOLUME
                                   ^^^^^^^^^^^^^^
NameError: name 'MAX_HTD_VOLUME' is not defined
```

**Comment by UngluedChalice** [comment]
Sorry for the confusion about the Lync 6, I ended up deleting that because I don't have that system and I can't test it and I don't know what I'm doing. 

So the `'MAX_HTD_VOLUME' is not defined` is something that someone else added on the repo that I forked after I forked it, so I don't have that in mine and I don't know what it does. So I didn't have that in my Lync12 when I updated it for HA 2025.1. However, the person for did the Lync6 fork did have it, so I didn't take it out when I did the quick update. 

Are you able to grab these and use them and see if they work? https://github.com/UngluedChalice/htd-lync12-home-assistant/commit/bd511f322c636c3ff99568d0534a4008a98d02af

**Comment by Noobitious** [comment]
Thank you for that. I had to get ChatGPT to fix a checksum line. After that I kept going, and had a lot of fun with ChatGPT. I ended up making a new fork with some added features: https://github.com/Noobitious/htd-lync6-home-assistant

Anyways, it definitely works with Lync6 now.

**Comment by UngluedChalice** [comment]
Well, looks like an official integration is coming.

https://community.home-assistant.io/t/official-support-for-htd-is-coming/822168?u=ungluedchalice

**Comment by theharshl** [comment]
> @Noobitious and @theharshl please try the updated media_player.py and see if you get any errors. Please report back!

I'm really sorry I wasn't able to test right away! I had quite a busy weekend. It sounds like it is working well. I have held back my HA 2025.1 upgrade because of the HTD inegration breaking, but it sounds like you guys have mended it. Thank you so much for that. I will give it a try.

Also, thank you for pointing out the forthcoming official integration, that is very exciting! Thanks again for your work guys, it is much appreciated.
